easy_admin:
    entities:
        Annonce :
                class:
                        App\Entity\Annonce
                list:
                        title: 'Annonces périmées'
                        dql_filter: 'entity.expiredAt < CURRENT_TIMESTAMP()'

                        actions:         
                                 - { name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary' }
                                 - { name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger' }
                
                        fields : 
                                
                                - { property : 'entete' }
                                - { property : 'corps' }
                                - { property : 'expiredAt' }

                form :
                        fields : 
                                - { property : 'rubrique' }
                                - { property : 'entete' }
                                - { property : 'corps' }

                disabled_actions:
                                ['edit', 'new']
                
                                