easy_admin:
    entities:
            User:
              class : App\Entity\User
              # role_prefix: ROLE_ADMIN   
              list:
                title: 'Utilisateurs'
                actions: ['-new']
                fields : 
                      - { property : 'Email', label: 'mail'}
                      - { property : 'First name', label: 'prenom'}
                      - { property : 'Last name', label: 'nom'}

                
                            